name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      approve_changes:
        description: "Approve Liquibase changes to apply to the database?"
        required: true
        default: "no"
        type: choice
        options:
          - yes
          - no

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo_cicd
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build Application
        run: ./gradlew clean build --info

      - name: Run unit and integration tests
        run: ./gradlew test

      - name: Preview Liquibase SQL
        run: |
          ./gradlew updateSQL --args="--changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml" > liquibase_sql_preview.txt
          echo "Preview the SQL changes."
          cat liquibase_sql_preview.txt

      - name: Validate Liquibase Changelog
        run: |
          ./gradlew validate --args="--changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml"

      - name: Check Approval
        if: ${{ github.event.inputs.approve_changes == 'no' }}
        run: |
          echo "Changes not approved. Stopping deployment."
          exit 1

      - name: Apply Liquibase Changes
        if: ${{ github.event.inputs.approve_changes == 'yes' }}
        run: |
          echo "Applying Liquibase changes to the database."
          ./gradlew update
