name: Liquibase Apply Pipeline

on:
  workflow_dispatch:

jobs:
  liquibase-apply:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo_cicd
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Preview Liquibase SQL
        id: liquibase_preview
        run: |
          ./gradlew updateSQL --args="--changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml" > liquibase_sql_preview.txt
          echo "Preview the SQL changes."
          cat liquibase_sql_preview.txt

      - name: Apply Liquibase Changes
        run: ./gradlew update
