name: Liquibase Apply Pipeline

on:
  workflow_dispatch:

jobs:
  liquibase-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Apply Liquibase Changes
        run: ./gradlew update
